name: Ejecutar bot de noticias

on:
  schedule:
    - cron: '13 8 * * *'  # Ejecutar a las 8:13 AM UTC-6 (CDMX)
  workflow_dispatch:       # Permite ejecutar manualmente también

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar bot
        run: python main.py
        env:
          GMAIL_USUARIO: ${{ secrets.GMAIL_USUARIO }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
