name: Ejecutar bot de noticias diario

on:
  schedule:
    - cron: '35 17 * * *' # Todos los días a las 8:00 AM UTC
  workflow_dispatch:     # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script
        env:
          GMAIL_USUARIO: ${{ secrets.GMAIL_USUARIO }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python NewsBot.py
  